source 'https://rubygems.org'

ruby '3.4.5'

gem 'rails', '~> 7.2.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 6.4'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.16.0', require: false
gem 'pg_search', '~> 2.3.6'
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 2.0'

# Is this needed, if I am sourcing the .env file in docker-compose?
# gem 'dotenv-rails', '~> 2.7.6'

group :development do
  gem 'listen', '~> 3.8'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.1.0'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri]
end

